### ISSUE TITLE
opening modelfile in gensim

### ISSUE THREAD

**Issue by transfluxus** [ray1007/pytorch-word2vec#6]
Thanks for the fix.
I would go on using gensim to compare it in terms of training-speed and accuracy!

I don't know how you further use your model but I can imagine some people would like to use it in gensim. The saved model however is not loadable in gensim. But there is an easy fix.
Replace all tabs \t with a single space and it works!

but it's up to you. More of a suggestion. Or maybe there is a standard format

**Comment by ray1007** [comment]
No problem! I think `gensim` should be faster, providing it uses pre-computed sigmoid table, scipy BLAS, and cython-level multi-threading. 

In my case, either whitespace or `\t` are fine, and I guess there is no such "standard" format. Making the embedding re-usable in `gensim` sounds good, it's done in the current commit. Thanks for the suggestion! 

Tzu-Ray
